[project]
name = "inh"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "pillow>=11.3.0",
    "streamlit>=1.50.0",
    "streamlit-drawable-canvas>=0.9.3",
]
